/*
 Name:		FramEink.ino
 Created:	10/16/2022 9:17:34 PM
 Author:	rudipirani
*/
/*
   3-Google_calendar_example for e-radionica.com Inkplate 10
   For this example you will need only USB cable and Inkplate 10.
   Select "Inkplate 10(ESP32)" from Tools -> Board menu.
   Don't have "Inkplate 10(ESP32)" option? Follow our tutorial and add it:
   https://e-radionica.com/en/blog/add-inkplate-6-to-arduino-ide/

   This project shows you how Inkplate 10 can be used to display
   events in your Google Calendar using their provided API

   For this to work you need to change your timezone, wifi credentials and your private calendar url
   which you can find following these steps:

    1. Open your google calendar
    2. Click the 3 menu dots of the calendar you want to access at the bottom of left hand side
    3. Click 'Settings and sharing'
    4. Navigate to 'Integrate Calendar'
    5. Take the 'Secret address in iCal format'

   (https://support.google.com/calendar/thread/2408874?hl=en)

   Want to learn more about Inkplate? Visit www.inkplate.io
   Looking to get support? Write on our forums: http://forum.e-radionica.com/en/
   11 February 2021 by e-radionica.com
*/

// Next 3 lines are a precaution, you can ignore those, and the example would also work without them
//#ifndef ARDUINO_INKPLATE10
//#error "Wrong board s-election for this example, please select Inkplate 10 in the boards menu."
//#endif

// Include Inkplate library to the sketch
#include "Inkplate.h"
#include <SDPhoto.h>
#include <EventClass.h>

// Including fonts
#include "fonts.h"
#include "u8g2_for_adafruit_gfx.h"

// Including icons generated by the py file
#include "icons_1bit.h"

// Includes
#include <Network.h>
#include <CommonFunctions.h>
#include <WiFiAccessPoint/WiFiAPSettings.h>
#include <algorithm>
#include <ctime>

const bool DEBUG = false;

// WiFi Credentials ---------------
String ssid;
String pass;
// CALENDAR -----------------
String calendarURL;
//String calendarURL = "https://calendar.google.com/calendar/ical/e9jkn0qjeetjm2mkkvhubtlvrk%40group.calendar.google.com/private-7a399955cd5efd535cac7599422df2b0/basic.ics";

// Indica l'offset in secondi da applicare alle date, relativo al timeZone della location Meteo impostata.
RTC_DATA_ATTR int timeZone = 0;

// Set to 3 to flip the screen 180 degrees
#define ROTATION 1
#define ROWS 2
#define COLUMNS 3
//---------------------------
int WIDTH, HEIGHT;
int HEIGHT_PHOTO = 600;
int cellWidth, cellHeight;
// header size for calendar name and current Time
int headerCalendarName = 30;
// header height, for day info
int headerDay = 40;
// margini della tabella
int marginLeft = -3;
int marginRight = 0;
int marginUp = 0;
int marginDown = -2;
int colorGrid = 2;
float thickLineGrid = 2.0;
const uint16_t colorCalendarTitle = 0;
const uint16_t colorCalendarTime = 0;
const uint16_t colorCalendarLocation = 0;

// WiFi AP Settings
WiFiAPSettingsClass* wiFiAPSettings = NULL;
RTC_DATA_ATTR bool settingsOK = false; // viene messa a true dopo che vengono settati i parametri, 
// cos� non compare pi� la pagina dei Settings

// WEATHER  -----------------
// City filled by query
#define icon_weather_height 96
// height of the weather strip
int headerWeather = 40; // qui verr� aggiunto icon_height

// Constants used for drawing icons
char abbrs[11][4] = { "13d", "sl", "h", "11d", "10d", "lr", "09d", "04d", "02d", "01d", "03d" };
const uint8_t* logos[16] = { icon_sn, icon_sl, icon_h, icon_t, icon_hr, icon_lr, icon_s, icon_hc, icon_lc, icon_c, icon_hc };
const uint8_t* color_icons[16] = { icon_s_sn, icon_s_sl, icon_s_h,  icon_s_t,  icon_s_hr,
                              icon_s_lr, icon_s_s,  icon_s_hc, icon_s_lc, icon_s_c, icon_s_hc };
const uint8_t* moon_phases_1bit[27] = { moon_phase_0, moon_phase_0_04, moon_phase_0_08, moon_phase_0_11, moon_phase_0_15,
                                    moon_phase_0_18, moon_phase_0_21, moon_phase_0_25, moon_phase_0_29, moon_phase_0_33,
                                    moon_phase_0_36, moon_phase_0_40, moon_phase_0_43, moon_phase_0_47, moon_phase_0_50,
                                    moon_phase_0_54, moon_phase_0_58, moon_phase_0_61, moon_phase_0_65, moon_phase_0_69,
                                    moon_phase_0_73, moon_phase_0_77, moon_phase_0_81, moon_phase_0_85, moon_phase_0_89,
                                    moon_phase_0_93, moon_phase_0_96 };
const int moon_phase_icon_size = moon_phase_0_w;

// Go to sleep before checking again
long long time_sleeping = 60ll; // [minutes] 180' = 3h sleep

// Initiate out Inkplate object
Inkplate display(INKPLATE_3BIT);
// SDPhoto Object
SDPhotoClass* sdPhoto = NULL;
RTC_DATA_ATTR uint counterPortrait = 0;
RTC_DATA_ATTR uint counterLandscape = 0;
RTC_DATA_ATTR bool stateCalendar = true; // true: Calendar+landscapePhoto ; false: portraitPhoto

// Our networking functions, see Network.cpp for info
Network network;

// Variables for time and raw event info
char dateTime[64];
char* dataCalendar;

// Here we store calendar entries
EventClass entries[EventClass::MAX_CALENDAR_EVENTS];

// All our functions declared below setup and loop
void drawCalendarName();
void drawTime();
void drawCalendarSize();
void drawBattery();
void drawGrid();
//void getToFrom(char* dst, char* from, char* to, int* day, int* timeStamp, bool correctTimeZone);
bool drawEvent(EventClass* event, int day, int beginY, int maxHeigth, int* heigthNeeded);
int cmpEvents(const void* a, const void* b);
void drawCalendarData();
void drawWeatherIcon(int beginX, int beginY, int heightIcon);
void drawWeatherStrip();

void setup()
{
    time_t nowAwakeEpoch = network.getNowEpoch(false);
    if (DEBUG)
    {
        Serial.begin(115200);
        Serial.println("Inizializzo...");
    }

    // calcolo le variabili iniziali in base all'orientamento
    if (ROTATION == 0 | ROTATION == 2)
    {
        WIDTH = display.width(); // 1200
        HEIGHT = display.height(); // 825
    }
    else {
        WIDTH = display.height();
        HEIGHT = display.width();
    }
    // Se stampo due righe di Calendario, allora non stampo la foto in modalit� Portrait
    if (ROWS > 1)
    {
        HEIGHT_PHOTO = 0;
    }
    cellWidth = (WIDTH - marginLeft - marginRight) / COLUMNS;
    cellHeight = (HEIGHT - HEIGHT_PHOTO - headerCalendarName - marginUp - marginDown) / ROWS;

    headerWeather += icon_weather_height;

    // Initial display settings
    display.begin();

    display.setRotation(ROTATION);
    display.setTextWrap(false);
    display.cp437(true);

    settingsOK = true; // debug: quando true non mostra la schermata di settings
    wiFiAPSettings = new WiFiAPSettingsClass();
    if (!settingsOK)
    {
        wiFiAPSettings->initAP();
        drawSettings();
        wiFiAPSettings->loop(); // esco dopo 10 minuti
        settingsOK = true;
        drawSettingsDone();
    }
    ssid = wiFiAPSettings->SSID_User;
    pass = wiFiAPSettings->PWD_User;
    network.latitude = atoff(wiFiAPSettings->Latitude_User.c_str());
    network.longitude = atoff(wiFiAPSettings->Longitude_User.c_str());
    calendarURL = wiFiAPSettings->ICALID_User;

    display.setTextColor(0, 7);

    sdPhoto = new SDPhotoClass(&display);

    //Serial.print("ssid: ");
    //Serial.println(ssid);
    //Serial.print("pass: ");
    //Serial.println(pass);
    //Serial.print("calendarURL: ");
    //Serial.println(calendarURL);
    //Serial.print("sd init: ");
    //Serial.println(sdPhoto->initOk);
    //Serial.printf("display sd init: %d\n", display.sdCardInit());

    //stateCalendar = false; // debug
    if (!stateCalendar)
    {
        // Photo
        counterPortrait = -1; // attivo il random mode
        display.clearDisplay();
        sdPhoto->drawImageFromSD(0, 0, SDPhotoClass::PhotoOrientation::portrait, counterPortrait);
    }
    else {

        if (DEBUG)
            Serial.println("network.begin");
        network.begin(); // stampo su seriale la data e ora attuale
        // Controllo che siano passati almeno 15 minuti dall'ultimo risveglio
        if (DEBUG)
            Serial.printf("last awake: %d\n", checkLastAwake(15ll, network.getNowEpoch(true)));
        
        // ---  WEATHER  ---
        //network.getDaysLabel(days[0], days[1], days[2], days[3]);
        network.getDataFromOpenWeather(&timeZone, temps_min[0], temps_min[1], temps_min[2], temps_min[3], temps_min[4], temps_min[5], currentTemp,
            temps_max[0], temps_max[1], temps_max[2], temps_max[3], temps_max[4], temps_max[5],
            probabilityOfRain[0], probabilityOfRain[1], probabilityOfRain[2], probabilityOfRain[3], probabilityOfRain[4], probabilityOfRain[5],
            precipitation_mm[0], precipitation_mm[1], precipitation_mm[2], precipitation_mm[3], precipitation_mm[4], precipitation_mm[5],
            currentWind, currentTime, nameWeather[0], nameWeather[1], nameWeather[2], nameWeather[3], nameWeather[4], nameWeather[5],
            abbr_days[0], abbr_days[1], abbr_days[2], abbr_days[3], abbr_days[4], abbr_days[5],
            &moon_phase[0], &moon_phase[1], &moon_phase[2], &moon_phase[3], &moon_phase[4], &moon_phase[5],
            sunrise_time[0], sunrise_time[1], sunrise_time[2], sunrise_time[3], sunrise_time[4], sunrise_time[5], 
            sunset_time[0], sunset_time[1], sunset_time[2], sunset_time[3], sunset_time[4], sunset_time[5]);

        // ---  CALENDAR  ---
        if (calendarURL != "") {
            dataCalendar = (char*)ps_malloc(SIZE_CALENDAR_DATA); // alloco 2Mb su RAM extra del ESP32
            // Keep trying to get data if it fails the first time
            calendarSize = 0;
            while (calendarSize < 2)
            {
                calendarSize = network.getDataCalendar(dataCalendar);
                if (DEBUG)
                    Serial.println("Failed getting data, retrying");
                delay(1000);
            }
        }

        //Serial.println(data); // stampo i dati grezzi del calendario
        // Drawing all data, functions for that are above
        display.clearDisplay();

        drawBattery();
        if (calendarURL != "") {
            drawCalendarData();
            drawCalendarName();
        }
        drawGrid();
        drawCalendarSize();
        drawTime();

        drawWeatherStrip();

        // Photo
        if (ROWS < 2)
        {
            // Attivo modalit� Random su Photo
            counterLandscape = -1;
            sdPhoto->drawImageFromSD(0, HEIGHT_PHOTO + 3, SDPhotoClass::PhotoOrientation::landscape, counterLandscape);
        }
    }
    // Toggle the state of the InkPlate
    stateCalendar = !stateCalendar;
    delay(300);

    // Can't do partial due to deepsleep
    display.display();

    if (DEBUG)
        Serial.printf("counterPortrait: %d, counterLandscape: %d\n", counterPortrait, counterLandscape);

    // Se si sveglia tra le 23:00 e l' 1:59, imposto a 6 ore il tempo di sleep
    int timeHour;
    network.getTimeHour(&timeHour, 0);
    if (timeHour >= 23 || timeHour < 2)
    {
        time_sleeping = 360ll; // 6h sleep
    }
    if (DEBUG)
        Serial.printf("Sleep time [us]: ", time_sleeping * MIN_2_MICROSEC);

    // Valuto il tempo di computazione per fare in modo che si svegli sempre ogni ora
    long long computationTime = 0;
    //Serial.printf("Start: %d , End: %d\n", nowAwakeEpoch, network.getNowEpoch(false));
    if (nowAwakeEpoch > 0)
    {
        computationTime = (long long)(network.getNowEpoch(false) - nowAwakeEpoch) * SEC_2_MICROSEC;
    }
    //Serial.printf("Computation Time: %d\n", computationTime / SEC_2_MICROSEC);

    esp_sleep_enable_timer_wakeup(time_sleeping * MIN_2_MICROSEC - computationTime);
    (void)esp_deep_sleep_start();
}

void loop()
{
    // Never here
}

// Function for drawing calendar info
void drawCalendarName()
{
    // Setting font and color
    display.setTextColor(0, 7);
    display.setFont(&FreeSans12pt7b);
    display.setTextSize(1);

    display.setCursor(marginLeft + 20, marginUp + 22);

    // Find email in raw data
    char temp[64];
    char* start = strstr(dataCalendar, "X-WR-CALNAME:");

    // If not found return
    if (!start)
        return;

    // Find where it ends
    start += 13;
    char* end = strchr(start, '\n');

    strncpy(temp, start, end - start - 1);
    temp[end - start - 1] = 0;

    // Print it
    display.println(temp);
}

// Drawing what time it is
void drawTime()
{
    // Initial text settings
    display.setTextColor(0, 7);
    display.setFont(&FreeSans12pt7b);
    display.setTextSize(1);

    display.setCursor(marginLeft + 500, marginUp + 22);

    // Our function to get time
    network.getTime(dateTime);

    int t = dateTime[16];
    dateTime[16] = 0;
    display.println(dateTime);
    dateTime[16] = t;
}

// Drawing the size of the calendar
void drawCalendarSize()
{
    // Initial text settings
    display.setTextColor(0, 7);
    display.setFont(&FreeSans12pt7b);
    display.setTextSize(1);

    display.setCursor(marginLeft + 200, marginUp + 22);

    display.printf("CalendarSize: %d",calendarSize);
}

void drawBattery()
{
    // Initial text settings
    display.setTextColor(0, 7);
    display.setFont(&FreeSans12pt7b);
    display.setTextSize(1);

    display.setCursor(WIDTH - marginRight - 50, marginUp + 22);

    display.println(display.readBattery());
    //  double voltage = display.readBattery();

}

// Draw lines in which to put events
void drawGrid()
{
    // upper left and low right coordinates
    int x1 = marginLeft, y1 = headerCalendarName + marginUp;
    int x2 = WIDTH - marginRight, y2 = HEIGHT - HEIGHT_PHOTO - marginDown;

    // Columns and rows
    int n = ROWS, m = COLUMNS;

    // Banda leggera di intestazione, dietro alle label dei giorni
    for (int i = 0; i < n; i++)
    {
        // Disegno la banda con colore light_gray
        for (size_t row = 0; row < headerDay; row += light_gray_h)
        {
            for (size_t col = 0; col < x2; col += light_gray_w)
            {
                display.drawBitmap3Bit(x1 + col, y1 + row + (float)i * (float)(y2 - y1) / (float)n, light_gray, light_gray_w, light_gray_h);
            }
        }
        // Disegno una linea di separazione leggermente pi� scura del light_gray
        display.fillRect(x1, (int)((float)y1 + headerDay - thickLineGrid + (float)i * (float)(y2 - y1) / (float)n), (x2 - x1), thickLineGrid, 6);

    }

    // Line drawing
//    display.drawThickLine(x1, y1 + headerDay, x2, y1 + headerDay, colorGrid, thickLineGrid);
    for (int i = 0; i < n + 1; ++i)
    {
        // Riga orizzontale sopra header
        display.drawThickLine(x1, (int)((float)y1 + (float)i * (float)(y2 - y1) / (float)n), x2,
            (int)((float)y1 + (float)i * (float)(y2 - y1) / (float)n), colorGrid, thickLineGrid);
        // Riga orizzontale sotto header
  //        display.drawThickLine(x1, (int)((float)y1 + headerDay + (float)i * (float)(y2 - y1) / (float)n), x2,
  //                              (int)((float)y1 + headerDay + (float)i * (float)(y2 - y1) / (float)n), colorGrid+4, thickLineGrid);
    }
    for (int i = 0; i < m + 1; ++i)
    {
        // Righe verticali
        display.drawThickLine((int)((float)x1 + (float)i * (float)(x2 - x1) / (float)m), y1,
            (int)((float)x1 + (float)i * (float)(x2 - x1) / (float)m), y2, colorGrid, thickLineGrid);

    }
    // Stampo la scritta dei giorni del calendario
    display.setFont(&FreeSansBold12pt7b);
    for (int i = 0; i < m * n; ++i)
    {
        // Display day info using time offset
        char temp[64];
        network.getTime(temp, i * 3600L * 24);
        temp[10] = 0;

        display.setCursor(70 + (int)((float)x1 + (float)(i % m) * (float)(x2 - x1) / (float)m), y1 + headerDay - 13 + (int)(i / m) * (float)(y2 - y1) / (float)n);
        display.println(temp);
    }
}

// Function to draw event
bool drawEvent(EventClass* event, int day, int beginY, int maxHeigth, int* heigthNeeded)
{
    // Upper left coordinates
    int padLeftRight = 6; // margin from grid to event box
    int xLeftBox = marginLeft + cellWidth * (day % COLUMNS) + padLeftRight;
    int xRightBox = xLeftBox + cellWidth - 2 * padLeftRight;
    int yUpBox = beginY + 3;
    int marginYDownBox = 3;
    int marginTextEvent = 8; // margine dx e sx del titolo dell'evento
    int xStartTitle = xLeftBox + marginTextEvent;
    int interlinea = -15; // nel titolo dell'evento indica la distanza tra una riga e la successiva

    // Setting text font
    display.setFont(&FreeSansBold16pt7b);
    display.setTextColor(colorCalendarTitle);
    //    // Draw background // lascio commentato, risulta troppo scuro
    //    display.fillRect(x1, y1, cellWidth - 2 * padLeftRight, 110, 6);

    // Some temporary variables
    int n = 0;
    char line[128];

    // Insert line brakes into setTextColor
    int lastSpace = -100;
    display.setCursor(xStartTitle, beginY + 50); // offset tra la linea alta della griglia e l'inizio del testo
    //for (int i = 0; i < min(EventClass::MAX_N_CHAR_TITLE_CALENDAR, (int)strlen(event->name)); ++i)
    for (int i = 0; i < min(65, (int)strlen(event->name)); ++i)
    {
        // Se il primo carattere � uno spazio, lo salto
        if (n == 0 && event->name[i] == ' ')
            i++;

        // Copy name letter by letter and check if it overflows space given
        line[n] = event->name[i];
        if (line[n] == ' ')
            lastSpace = n;
        line[++n] = 0;

        int16_t xt1, yt1;
        uint16_t w, h;

        // Gets text bounds
        display.getTextBounds(line, 0, 0, &xt1, &yt1, &w, &h);

        // Scrivo linea per linea in modo che posso usare l'interlinea
        // Char out of bounds, put in next line
        if (w > xRightBox - xLeftBox - 2 * marginTextEvent)
        {
            // Ho superato la dimensione massima, quindi torno indietro di un carattere e stampo la stringa
            i--;
            line[--n] = 0;

            // if there was a space 5 chars before, break line there 
            // and print the whole word in the next line.
            if (n - lastSpace < 5)
            {
                i -= n - lastSpace - 1;
                line[lastSpace] = 0;
            }
            else
            {
                i--;
                line[--n] = '-';
            }

            // Print text line
            display.setCursor(xStartTitle, display.getCursorY() + interlinea);
            display.println(line);

            // Clears line (null termination on first charachter)
            line[0] = 0;
            n = 0;
        }
    }

    // display last line of text
    // Pu� capitare che vado a capo e la prima riga � il terminatore, in quel caso non stampo niente.
    if (line[0] != 0)
    {
        display.setCursor(xStartTitle, display.getCursorY() + interlinea);
        display.println(line);
    }

    // Print time
    // Set cursor on same x but change y
    display.setCursor(xStartTitle, display.getCursorY() - 15);
    display.setFont(&FreeSans12pt7b);

    // if theres a location print it
    if (strlen(event->location) > 1)
    {
        display.setTextColor(colorCalendarTime);
        display.println(event->time);

        display.setCursor(xStartTitle, display.getCursorY() - 2);

        char line[128] = { 0 };
        display.setTextColor(colorCalendarLocation);

        for (int i = 0; i < strlen(event->location); ++i)
        {
            line[i] = event->location[i];
            line[i + 1] = 0;

            int16_t xt1, yt1;
            uint16_t w, h;

            // Gets text bounds
            display.getTextBounds(line, 0, 0, &xt1, &yt1, &w, &h);

            if (w > xRightBox - xLeftBox - 2 * marginTextEvent)
            {
                for (int j = i - 1; j > max(-1, i - 4); --j)
                    line[j] = '.';
                line[i] = 0;
            }
        }

        display.print(line);
    }
    else
    {
        display.setTextColor(colorCalendarTime);
        display.print(event->time);
    }

    int yDownBox = display.getCursorY() + 7 + marginYDownBox;

    // Draw event rect bounds
    display.drawThickLine(xLeftBox, yUpBox, xLeftBox, yDownBox, 3, thickLineGrid);
    display.drawThickLine(xLeftBox, yDownBox, xRightBox, yDownBox, 3, thickLineGrid);
    display.drawThickLine(xRightBox, yDownBox, xRightBox, yUpBox, 3, thickLineGrid);
    display.drawThickLine(xRightBox, yUpBox, xLeftBox, yUpBox, 3, thickLineGrid);

    // Set how high is the event
    *heigthNeeded = display.getCursorY() + 12 - yUpBox;

    // Return is it overflowing
    return display.getCursorY() < maxHeigth - 100; // ipotizzo che il prossimo evento sia alto 100 pixel
    // se rimangono pi� di 100 pixel, il prossimo evento viene mostrato, se � pi� alto di 100 px vengono mostrati
    // solo i primi 100 px (3 righe)
}

// Struct event comparison function, by timestamp, used for qsort later on
int cmpEvents(const void* a, const void* b)
{
    EventClass* entryA = (EventClass*)a;
    EventClass* entryB = (EventClass*)b;

    return (entryA->timeStamp - entryB->timeStamp);
}

// Main data drawing data
void drawCalendarData()
{
    char* beginEvt = dataCalendar + 1;
    char* endCal = dataCalendar + strlen(dataCalendar) - 1;

    // Creo le epoch della finestra di inizio e fine giorni da visualizzare.
    // Finestra � dalle 00:00 del primo giorno alle 23:59 dell'ultimo giorno.
    time_t epochFirstDayShown = resetEpochOf(network.getNowEpoch(true), 
                                             false,
                                             false,
                                             false,
                                             true,
                                             true,
                                             true);
    time_t epochLastDayShown = epochFirstDayShown + COLUMNS * ROWS * DAYS_2_SEC - 1;

    int entriesNum = parseCalendarEvents(entries, beginEvt, endCal, timeZone, epochFirstDayShown, epochLastDayShown);

    // Sort entries by time
    qsort(entries, entriesNum, sizeof(EventClass), cmpEvents);
    if (DEBUG)
        Serial.printf("Eventi nel calendario: %d\n", entriesNum);
    
    // Events displayed and overflown counters
    int columns[COLUMNS * ROWS] = { 0 };
    bool clogged[COLUMNS * ROWS] = { 0 };
    int cloggedCount[COLUMNS * ROWS] = { 0 };

    // Displaying events one by one
    for (int i = 0; i < entriesNum; ++i)
    {
        //Serial.println(entries[i].day);
        // If column overflowed just add event to not shown
        if (entries[i].day != -1 && clogged[entries[i].day])
            ++cloggedCount[entries[i].day];
        if (entries[i].day == -1 || clogged[entries[i].day])
            continue;

        // We store how much height did one event take up
        int shift = 0;
        int padDown = 5;
        int padUp = 8;
        bool s = drawEvent(&entries[i], entries[i].day, columns[entries[i].day] + (entries[i].day / COLUMNS) * cellHeight + marginUp + headerCalendarName + headerDay + headerWeather + padUp,
            (entries[i].day / COLUMNS) * cellHeight + marginUp + headerCalendarName + cellHeight, &shift);

        if (DEBUG)
            Serial.println(shift);
        columns[entries[i].day] += shift + padDown;

        // If it overflowed, set column to clogged and add one event as not shown
        if (!s)
        {
            if (DEBUG)
                Serial.println("Clogged event");
            //            ++cloggedCount[entries[i].day];
            clogged[entries[i].day] = 1;
        }
    }

    // Display not shown events info
    for (int i = 0; i < COLUMNS * ROWS; ++i)
    {
        if (clogged[i] && cloggedCount[i] > 0)
        {
            // Draw notification showing that there are more events than drawn ones
            int xBegin = marginLeft + cellWidth * (i % COLUMNS) + thickLineGrid;
            int yBegin = marginUp + headerCalendarName + (i / COLUMNS) * cellHeight + cellHeight - 23;
            display.fillRoundRect(5 + xBegin, yBegin, cellWidth - 10, 20, 10, 6);
            display.setCursor(15 + xBegin, yBegin + 15);
            //            display.setTextColor(7, 0);
            display.setTextColor(7, WHITE);
            display.setFont(&FreeSans9pt7b);
            display.print(cloggedCount[i]);
            display.print(" more event");
            // Se c'� pi� di un evento, metto il plurale ad events
            if (cloggedCount[i] > 1)
            {
                display.print("s");
            }
        }
    }
}

// ====  WEATHER drawing  ====
// ICON
void drawWeatherIcon(int beginX, int beginY, int day)
{
    int color = 3;
    // Icon
    for (int i = 0; i < 11; ++i)
    {
        // If found draw specified icon
        if (strcmp(abbr_days[day], abbrs[i]) == 0)
            display.drawBitmap(beginX, beginY, color_icons[i], icon_weather_height, icon_weather_height, color);
    }
}
// weather info label
int drawWeatherLabel(int x, int y, int day)
{
    //    // Searching for weather state abbreviation
    //    for (int i = 0; i < 10; ++i)
    //    {
    //        // If found draw specified icon
    //        if (strcmp(abbrs[i], currentWeatherAbbr) == 0)
    //            display.drawBitmap(50, 50, logos[i], 152, 152, BLACK);
    //    }

        // Draw weather state
    display.setTextColor(BLACK, WHITE);
    display.setFont(&FreeSans18pt7b);
    display.setTextSize(1);
    display.setCursor(x, y);
    display.println(nameWeather[day]);

    int16_t x1, y1;
    uint16_t w, h;
    display.getTextBounds(nameWeather[day], 0, 0, &x1, &y1, &w, &h); //calc width of new string
    return x + w;
}
// TEMPERATURE
void drawWeatherTemp(int x, int y, int day)
{
    // Temp Max
    display.setFont(&FreeSans18pt7b);
    display.setCursor(x, y + 2);
    display.print(temps_max[day]);
    display.setFont(&FreeSans12pt7b);
    //display.println("� C");
    // Temp Min
    display.setFont(&FreeSans18pt7b);
    display.setCursor(x, y + 38);
    display.print(temps_min[day]);
    display.setFont(&FreeSans12pt7b);
    //display.println(F("� C"));

    int16_t x1, y1;
    uint16_t wMax, wMin, h;
    display.getTextBounds(temps_max[day], 0, 0, &x1, &y1, &wMax, &h);
    display.getTextBounds(temps_min[day], 0, 0, &x1, &y1, &wMin, &h);
    display.drawBitmap3Bit(x + max(wMax, wMin)*2, y - 28, termometro, termometro_w, termometro_h);
}
// SUNSET - SUNRISE
void drawSunriseSunsetTime(int x, int y, int day)
{
    // Sunrise
    display.setFont(&FreeSans12pt7b);
    display.setCursor(x, y + icon_sunset_h + 20);
    display.print(sunrise_time[day]);
    // Sunset
    display.setFont(&FreeSans12pt7b);
    display.setCursor(x, y + icon_sunset_h + 40);
    display.print(sunset_time[day]);
    int16_t x1, y1;
    uint16_t w, h;
    display.getTextBounds(sunset_time[day], 0, 0, &x1, &y1, &w, &h); //calc width of new string

    int offsetXIcon = 0.5 * (w - icon_sunset_w);
    display.drawBitmap(x + offsetXIcon, y, icon_sunset, icon_sunset_w, icon_sunset_h, 7, 0);
}
// Probability Of Rain
void drawProbabilityOfRain(int x, int y, int day)
{
    int separator = 9;
    // Sunrise
    display.setTextColor(2);
    display.setFont(&FreeSansBold11pt7b);
    display.setCursor(x + icon_drop_w, y);
    display.print(probabilityOfRain[day]);
    display.setFont(&FreeSansBold7pt7b);
    display.setCursor(display.getCursorX() + 3, display.getCursorY() - 1);
    display.print("%");
    // Get string height
    int16_t x1, y1;
    uint16_t w, h;
    display.getTextBounds(probabilityOfRain[day], 0, 0, &x1, &y1, &w, &h); //calc width of new string
    // Sunset
    display.setFont(&FreeSansBold11pt7b);
    display.setCursor(x + icon_drop_w, y + h + separator);
    display.print(precipitation_mm[day]);
    display.setFont(&FreeSansBold7pt7b);
    display.setCursor(display.getCursorX() + 3, display.getCursorY() - 1);
    display.print("mm");

    int offsetYIcon = 0.5 * (2 * (h + separator) - icon_drop_h);
    display.drawBitmap3Bit(x, y - h * 1.3 + offsetYIcon, icon_drop, icon_drop_w, icon_drop_h);
}

void drawWeatherStrip()
{
    int padLeft = 15;
    int padUp = -1;
    int padDown = 5;
    for (int day = 0; day < COLUMNS * ROWS; day++)
    {
        int xBegin = marginLeft + cellWidth * (day % COLUMNS) + padLeft;
        int yBegin = marginUp + headerCalendarName + headerDay + (day / COLUMNS) * cellHeight + padUp;
        drawWeatherIcon(xBegin, yBegin + 5, day);
        int yWeatherLabel = yBegin + headerWeather - 4;
        int xEndWeatherLabel = drawWeatherLabel(xBegin, yWeatherLabel, day);
        drawWeatherTemp(xBegin + icon_weather_height + 12, yBegin + 40, day);
        drawSunriseSunsetTime(xBegin + icon_weather_height + 100, yBegin + 10, day);

        // If the weather icon is with rain, print the rain probability
        if (strcmp(abbr_days[day], "h") == 0 ||
            strcmp(abbr_days[day], "10d") == 0 ||
            strcmp(abbr_days[day], "lr") == 0 ||
            strcmp(abbr_days[day], "09d") == 0 ||
            strcmp(abbr_days[day], "13d") == 0) // Snow
        {
            drawProbabilityOfRain(xBegin + icon_weather_height + 8, yWeatherLabel - 19, day);
        }
        // Moon
        uint8_t index_moon = (uint8_t)round(moon_phase[day] * sizeof(moon_phases_1bit) / sizeof(moon_phases_1bit[0]));
        if (DEBUG)
            Serial.printf("index moon: %d\n", index_moon);
        display.drawBitmap(xBegin + cellWidth - moon_phase_icon_size - padLeft - 15,
            yBegin + headerWeather - moon_phase_icon_size,
            moon_phases_1bit[index_moon],
            moon_phase_icon_size, moon_phase_icon_size,
            7, 0);

        // Riga orizzontale in basso. Delimita tempo da eventi calendario
        display.drawThickLine(xBegin - padLeft + thickLineGrid, yBegin + headerWeather + padDown, xBegin - padLeft + cellWidth, yBegin + headerWeather + padDown, colorGrid + 3, thickLineGrid);
    }
}

void drawSettings()
{                              // This function updates screen with new data (text)
    display.clearDisplay();               // Clear frame buffer of display
    display.setFont(&FreeSans24pt7b);
    display.setTextWrap(false);            // If text does not fit on screen, send it to new line


    display.setTextColor(0);
    display.setCursor(15, 80);
    int x1 = 55; int y1 = 55;
    int x2 = x1 + WIDTH - 110;  int y2 = y1 + 92;
    // Disegno la banda con colore light_gray
    for (size_t row = y1+4; row < y2-4; row += light_gray_h)
    {
        for (size_t col = x1+4; col < x2-4; col += light_gray_w)
        {
            display.drawBitmap3Bit(col, row, light_gray, light_gray_w, light_gray_h);
        }
    }
    drawCentreString("SETTINGS", WIDTH / 2, 100);
    uint8_t thick = 5;
    for (size_t i = 0; i < thick; i++)
    {
        display.drawRoundRect(x1 + i, y1 + i, WIDTH - 110 - 2 * i,  92 - 2 * i, 10, 1);
    }

    display.setFont(&FreeSans18pt7b);
    display.setTextColor(2);
    display.setCursor(x1, 260); // Print out instruction on how to connect to Inkplate WiFi and how to open a web page
    display.print("1. Connect to ");
    display.setTextColor(0);
    display.print(wiFiAPSettings->SSID_AP_Settings);
    display.setTextColor(2);
    display.println(" WiFi");

    display.setCursor(x1, 370);
    display.println("2. Open your web browser and");
    display.setCursor(display.getCursorX() + 95, display.getCursorY());
    display.print("go to: ");

    display.setTextColor(0);
    //display.setCursor(35, 140);
    display.print("http://");
    display.print(wiFiAPSettings->serverIP);
    display.println('/');
    display.println();

    display.setTextColor(2);
    display.setCursor(x1, 520);
    display.println("3. Fill in the information and");
    display.setCursor(display.getCursorX() + 95, display.getCursorY());
    display.print("press ");
    display.setTextColor(0);
    display.print("Send to FramEInk! ");

    //display.fillRect(10, 240, 780, 4, INKPLATE_YELLOW);

    display.setTextColor(1);
    drawCentreString("This page will remain", WIDTH / 2, 800);
    display.println("");
    //fprintf("active for %s minutes", wiFiAPSettings->settingDuration);
    drawCentreString((String("active for ") + String(wiFiAPSettings->settingDuration) + String(" minutes")).c_str(), WIDTH / 2, display.getCursorY());

    // Draw rounded rect
    for (size_t i = 0; i < thick; i++)
    {
        display.drawRoundRect(x1 + i, display.getCursorY() - 135 + i, WIDTH - 1 - 110 - 2 * i, 200 - 2 * i, 10, 1);
    }

    // Draw rect around the edges
    for (size_t i = 0; i < thick; i++)
    {
        display.drawRect(i, i, WIDTH - 1 - 2 * i, HEIGHT - 1 - 2 * i, 1);
    }
    display.display(); // Send everything to screen (refresh the screen)
}


void drawSettingsDone()
{                              // This function updates screen with new data (text)
    display.clearDisplay();               // Clear frame buffer of display
    display.setFont(&FreeSans24pt7b);
    display.setTextWrap(false);            // If text does not fit on screen, send it to new line


    display.setTextColor(0);
    drawCentreString("SETTINGS SAVED", WIDTH / 2, 440);
    drawCentreString("WAIT LOADING...", WIDTH / 2, 510);
    uint8_t thick = 5;
    for (size_t i = 0; i < thick; i++)
    {
        display.drawRoundRect(55 + i, display.getCursorY() - 140, WIDTH - 1 - 110 - 2 * i, 200 - 2 * i, 10, 1);
    }
    display.display(); // Send everything to screen (refresh the screen)
}

void drawCentreString(const char* text, int x, int y)
{
    int16_t x1, y1;
    uint16_t w, h;
    display.getTextBounds(text, 0, 0, &x1, &y1, &w, &h); //calc width of new string

    //Serial.println(x);
    //Serial.println(y);
    //Serial.println(w);
    //Serial.println(h);
    //Serial.println("");
    display.setCursor(x - (w / 2), y + (h / 2));
    display.print(text);
}
