/*
 Name:		FramEink.ino
 Created:	10/16/2022 9:17:34 PM
 Author:	rudipirani
*/
/*
   3-Google_calendar_example for e-radionica.com Inkplate 10
   For this example you will need only USB cable and Inkplate 10.
   Select "Inkplate 10(ESP32)" from Tools -> Board menu.
   Don't have "Inkplate 10(ESP32)" option? Follow our tutorial and add it:
   https://e-radionica.com/en/blog/add-inkplate-6-to-arduino-ide/

   This project shows you how Inkplate 10 can be used to display
   events in your Google Calendar using their provided API

   For this to work you need to change your timezone, wifi credentials and your private calendar url
   which you can find following these steps:

    1. Open your google calendar
    2. Click the 3 menu dots of the calendar you want to access at the bottom of left hand side
    3. Click 'Settings and sharing'
    4. Navigate to 'Integrate Calendar'
    5. Take the 'Secret address in iCal format'

   (https://support.google.com/calendar/thread/2408874?hl=en)

   Want to learn more about Inkplate? Visit www.inkplate.io
   Looking to get support? Write on our forums: http://forum.e-radionica.com/en/
   11 February 2021 by e-radionica.com
*/

// Next 3 lines are a precaution, you can ignore those, and the example would also work without them
//#ifndef ARDUINO_INKPLATE10
//#error "Wrong board s-election for this example, please select Inkplate 10 in the boards menu."
//#endif

// Include Inkplate library to the sketch
#include "SDPhoto.h"
#include "Inkplate.h"

// Including fonts
#include "Fonts/FreeSans12pt7b.h"
#include "Fonts/FreeSans9pt7b.h"
#include "Fonts/FreeSansBold12pt7b.h"
#include "Fonts/FreeSansBold18pt7b.h"
#include "Fonts/FreeSans18pt7b.h"
#include "Fonts/Roboto_Light_36.h"

// Includes
#include "Network.h"
#include "CommonFunctions.cpp"
#include <algorithm>
#include <ctime>

// Including icons generated by the py file
#include "icons_1bit.h"

// CHANGE HERE ---------------
char ssid[] = "Baghini";
char pass[] = "lastanzadeibottoni";
// CALENDAR -----------------
char calendarURL[] = "https://calendar.google.com/calendar/ical/e9jkn0qjeetjm2mkkvhubtlvrk%40group.calendar.google.com/private-7a399955cd5efd535cac7599422df2b0/basic.ics";
int timeZone = 0;

// Set to 3 to flip the screen 180 degrees
#define ROTATION 1
#define ROWS 1
#define COLUMNS 3
//---------------------------
int WIDTH, HEIGHT;
int HEIGHT_PHOTO = 600;
int cellWidth, cellHeight;
// header size for calendar name and current Time
int headerCalendarName = 30;
// header height, for day info
int headerDay = 40;
// margini della tabella
int marginLeft = 3;
int marginRight = 3;
int marginUp = 0;
int marginDown = 0;
int colorGrid = 2;
float thickLineGrid = 2.0;


// WEATHER  -----------------
// City filled by query
char city[128] = "";
#define icon_height 96
// height of the weather strip
int headerWeather = 40; // qui verrà aggiunto icon_height

// Constants used for drawing icons
char abbrs[11][4] = { "13d", "sl", "h", "11d", "10d", "lr", "09d", "04d", "02d", "01d", "03d" };
const uint8_t* logos[16] = { icon_sn, icon_sl, icon_h, icon_t, icon_hr, icon_lr, icon_s, icon_hc, icon_lc, icon_c, icon_hc };
const uint8_t* color_icons[16] = { icon_s_sn, icon_s_sl, icon_s_h,  icon_s_t,  icon_s_hr,
                              icon_s_lr, icon_s_s,  icon_s_hc, icon_s_lc, icon_s_c, icon_s_hc };

RTC_DATA_ATTR char abbr_days[6][16];

// Variables for storing temperature
RTC_DATA_ATTR char temps_min[8][6] = {
    "0F",
    "0F",
    "0F",
    "0F",
    "0F",
    "0F",
};
RTC_DATA_ATTR char temps_max[8][6] = {
    "0F",
    "0F",
    "0F",
    "0F",
    "0F",
    "0F",
};
RTC_DATA_ATTR char predictability[8][6] = {
    "0F",
    "0F",
    "0F",
    "0F",
    "0F",
    "0F",
};
// Variables for storing days of the week
RTC_DATA_ATTR char days[8][4] = {
    "",
    "",
    "",
    "",
};
// Variables for storing current time and weather info
RTC_DATA_ATTR char currentTemp[16] = "0F";
RTC_DATA_ATTR char currentWind[16] = "0m/s";

RTC_DATA_ATTR char currentTime[16] = "9:41";

RTC_DATA_ATTR char nameWeather[6][32] = {
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
};


// Go to sleep before checking again
const long long time_sleeping = 60ll; // [minutes] 180' = 3h sleep
// Delay between API calls. Converts time_sleeping in minutes.
#define MIN_2_MICROSEC 60000000ll

// Initiate out Inkplate object
Inkplate display(INKPLATE_3BIT);
// SDPhoto Object
SDPhotoClass* sdPhoto = NULL;
RTC_DATA_ATTR uint counterPortrait = 0;
RTC_DATA_ATTR uint counterLandscape = 0;
RTC_DATA_ATTR bool stateCalendar = true; // true: Calendar+landscapePhoto ; false: portraitPhoto

// Our networking functions, see Network.cpp for info
Network network;

// Variables for time and raw event info
char date[64];
char* data;

// Struct for storing calender event info
struct entry
{
    char name[128];
    char time[128];
    char location[128];
    int day = -1;
    int timeStamp;
};

// Here we store calendar entries
int entriesNum = 0;
const int MAX_CALENDAR_EVENTS = 128;
entry entries[MAX_CALENDAR_EVENTS];

// All our functions declared below setup and loop
void drawInfo();
void drawTime();
void drawBattery();
void drawGrid();
void getToFrom(char* dst, char* from, char* to, int* day, int* timeStamp, bool correctTimeZone);
bool drawEvent(entry* event, int day, int beginY, int maxHeigth, int* heigthNeeded);
int cmp(const void* a, const void* b);
void drawCalendarData();
void drawWeatherIcon(int beginX, int beginY, int heightIcon);
void drawWeatherStrip();

void setup()
{
    Serial.begin(115200);
    Serial.println("Inizializzo...");

    // calcolo le variabili iniziali in base all'orientamento
    if (ROTATION == 0 | ROTATION == 2)
    {
        WIDTH = 1200;
        HEIGHT = 825;
    }
    else {
        WIDTH = 825;
        HEIGHT = 1200;
    }
    cellWidth = (WIDTH - marginLeft - marginRight) / COLUMNS;
    cellHeight = (HEIGHT - HEIGHT_PHOTO - headerCalendarName - marginUp - marginDown) / ROWS;

    headerWeather = headerWeather + icon_height;

    // Initial display settings
    display.begin();

    display.setRotation(ROTATION);
    display.setTextWrap(false);
    display.setTextColor(0, 7);

    sdPhoto = new SDPhotoClass(&display);

    // Initial screen clearing
    display.clearDisplay();

    // Attivo modalità Random su Photo
    counterPortrait = -1;
    counterLandscape = -1;

    if (!stateCalendar)
    {
        // Photo
        sdPhoto->drawImageFromSD(0, 0, SDPhotoClass::PhotoOrientation::portrait, counterPortrait);
    }
    else {

        network.begin(); // stampo su seriale la data e ora attuale
        // ---  WEATHER  ---
        network.getDaysLabel(days[0], days[1], days[2], days[3]);
        network.getDataFromMetaWeather(&timeZone, temps_min[0], temps_min[1], temps_min[2], temps_min[3], temps_min[4], temps_min[5], currentTemp,
            temps_max[0], temps_max[1], temps_max[2], temps_max[3], temps_max[4], temps_max[5],
            predictability[0], predictability[1], predictability[2], predictability[3], predictability[4], predictability[5],
            currentWind, currentTime, nameWeather[0], nameWeather[1], nameWeather[2], nameWeather[3], nameWeather[4], nameWeather[5],
            abbr_days[0], abbr_days[1], abbr_days[2], abbr_days[3], abbr_days[4], abbr_days[5]);

        // ---  CALENDAR  ---
        data = (char*)ps_malloc(1000000L); // alloco 1Mb su RAM extra del ESP32
        // Keep trying to get data if it fails the first time
        while (!network.getDataCalendar(data))
        {
            Serial.println("Failed getting data, retrying");
            delay(1000);
        }

        //Serial.println(data); // stampo i dati grezzi del calendario
        // Drawing all data, functions for that are above

        drawInfo();
        drawBattery();
        drawGrid();
        drawCalendarData();
        drawTime();

        drawWeatherStrip();

        // Photo
        sdPhoto->drawImageFromSD(0, HEIGHT_PHOTO + 3, SDPhotoClass::PhotoOrientation::landscape, counterLandscape);
    }
    // Toggle the state of the InkPlate
    stateCalendar = !stateCalendar;
    delay(1000);

    // Can't do partial due to deepsleep
    display.display();

    Serial.print("counterPortrait: ");
    Serial.println(counterPortrait);

    // Se si sveglia tra le 23:00 e l' 1:59, imposto a 6 ore il tempo di sleep
    int timeHour;
    network.getTimeHour(&timeHour, 0);
    if (timeHour >= 23 || timeHour < 2)
    {
        //time_sleeping = 360ll; // 6h sleep
    }
    Serial.print("Sleep time [us]: ");
    Serial.println(time_sleeping * MIN_2_MICROSEC);
    esp_sleep_enable_timer_wakeup(time_sleeping * MIN_2_MICROSEC);
    (void)esp_deep_sleep_start();
}

void loop()
{
    // Never here
}

// Function for drawing calendar info
void drawInfo()
{
    // Setting font and color
    display.setTextColor(0, 7);
    display.setFont(&FreeSans12pt7b);
    display.setTextSize(1);

    display.setCursor(marginLeft + 20, marginUp + 22);

    // Find email in raw data
    char temp[64];
    char* start = strstr(data, "X-WR-CALNAME:");

    // If not found return
    if (!start)
        return;

    // Find where it ends
    start += 13;
    char* end = strchr(start, '\n');

    strncpy(temp, start, end - start - 1);
    temp[end - start - 1] = 0;

    // Print it
    display.println(temp);
}

// Drawing what time it is
void drawTime()
{
    // Initial text settings
    display.setTextColor(0, 7);
    display.setFont(&FreeSans12pt7b);
    display.setTextSize(1);

    display.setCursor(marginLeft + 500, marginUp + 22);

    // Our function to get time
    network.getTime(date);

    int t = date[16];
    date[16] = 0;
    display.println(date);
    date[16] = t;
}

void drawBattery()
{
    // Initial text settings
    display.setTextColor(0, 7);
    display.setFont(&FreeSans12pt7b);
    display.setTextSize(1);

    display.setCursor(WIDTH - marginRight - 50, marginUp + 22);

    display.println(display.readBattery());
    //  double voltage = display.readBattery();

}

// Draw lines in which to put events
void drawGrid()
{
    // upper left and low right coordinates
    int x1 = marginLeft + thickLineGrid, y1 = headerCalendarName + marginUp;
    int x2 = WIDTH - marginRight, y2 = HEIGHT - HEIGHT_PHOTO - marginDown;

    // Columns and rows
    int n = ROWS, m = COLUMNS;

    display.fillRect(x1, y1, x2 - x1, 38, 6);

    // Line drawing
//    display.drawThickLine(x1, y1 + headerDay, x2, y1 + headerDay, colorGrid, thickLineGrid);
    for (int i = 0; i < n + 1; ++i)
    {
        // Riga orizzontale sopra header
        display.drawThickLine(x1, (int)((float)y1 + (float)i * (float)(y2 - y1) / (float)n), x2,
            (int)((float)y1 + (float)i * (float)(y2 - y1) / (float)n), colorGrid, thickLineGrid);
        // Riga orizzontale sotto header
  //        display.drawThickLine(x1, (int)((float)y1 + headerDay + (float)i * (float)(y2 - y1) / (float)n), x2,
  //                              (int)((float)y1 + headerDay + (float)i * (float)(y2 - y1) / (float)n), colorGrid+4, thickLineGrid);
    }
    for (int i = 0; i < m + 1; ++i)
    {
        // Righe verticali
        display.drawThickLine((int)((float)x1 + (float)i * (float)(x2 - x1) / (float)m), y1,
            (int)((float)x1 + (float)i * (float)(x2 - x1) / (float)m), y2, colorGrid, thickLineGrid);

    }
    // Stampo la scritta dei giorni del calendario
    display.setFont(&FreeSansBold12pt7b);
    for (int i = 0; i < m * n; ++i)
    {
        // Display day info using time offset
        char temp[64];
        network.getTime(temp, i * 3600L * 24);
        temp[10] = 0;

        display.setCursor(70 + (int)((float)x1 + (float)(i % m) * (float)(x2 - x1) / (float)m), y1 + headerDay - 13 + (int)(i / m) * (float)(y2 - y1) / (float)n);
        display.println(temp);
    }
}

// Format event times, example 13:00 to 14:00
void getToFrom(char* dst, char* from, char* to, int* day, int* timeStamp, bool correctTimeZone)
{
    // ANSI C time struct
    struct tm ltm = { 0 }, ltm2 = { 0 };
    char temp[128], temp2[128];
    strncpy(temp, from, 16);
    temp[16] = 0;

    // https://github.com/esp8266/Arduino/issues/5141, quickfix
    memmove(temp + 5, temp + 4, 16);
    memmove(temp + 8, temp + 7, 16);
    memmove(temp + 14, temp + 13, 16);
    memmove(temp + 16, temp + 15, 16);
    temp[4] = temp[7] = temp[13] = temp[16] = '-';

    // time.h function
    strptime(temp, "%Y-%m-%dT%H-%M-%SZ", &ltm);

    // create start and end event structs
    struct tm event, event2;
    time_t epoch = mktime(&ltm);
    // In alcuni casi viene passato l'orario già corretto del TimeZone, quindi non devo modificarlo.
    if (correctTimeZone)
    {
        epoch += (time_t)timeZone;
    }

    gmtime_r(&epoch, &event);

    strncpy(temp2, to, 16);
    temp2[16] = 0;

    // Same as above

    // https://github.com/esp8266/Arduino/issues/5141, quickfix
    memmove(temp2 + 5, temp2 + 4, 16);
    memmove(temp2 + 8, temp2 + 7, 16);
    memmove(temp2 + 14, temp2 + 13, 16);
    memmove(temp2 + 16, temp2 + 15, 16);
    temp2[4] = temp2[7] = temp2[13] = temp2[16] = '-';

    strptime(temp2, "%Y-%m-%dT%H-%M-%SZ", &ltm2);

    time_t epoch2 = mktime(&ltm2);
    if (correctTimeZone)
    {
        epoch2 += (time_t)timeZone;
    }

    gmtime_r(&epoch2, &event2);

    // Se l'evento dura almeno un giorno intero, nella label dell'orario scrivo 'All-day'.
    if (epoch2 - epoch >= 3600L * 24)
    {
        strncpy(dst, "All-day", 7);
    }
    else {
        // Scrivo l'ora di inizio in dst.
        strncpy(dst, asctime(&event) + 11, 5);
        dst[5] = '-';
        // Scrivo l'ora di fine in dst
        strncpy(dst + 6, asctime(&event2) + 11, 5);
    }
    dst[11] = 0;

    char days[COLUMNS * ROWS][64];

    // Definisco il giorno di inizio evento
    // Find UNIX timestamps for next days to see where to put event
    for (int i = 0; i < COLUMNS * ROWS; i++)
    {
        network.getTime(days[i], i * 24 * 3600);
    }

    *timeStamp = epoch;

    // Getting the time from our function in Network.cpp
    network.getTime(temp);
    for (int i = 0; i < COLUMNS * ROWS; i++)
    {
        if (strncmp(days[i], asctime(&event), 10) == 0)
        {
            *day = i;
            break;
        }
        else { // event not in next COLUMNS * ROWS days, don't display
            *day = -1;
        }
    }
}

// Function to draw event
bool drawEvent(entry* event, int day, int beginY, int maxHeigth, int* heigthNeeded)
{
    // Upper left coordinates
    int padLeftRight = 6;
    int x1 = marginLeft + cellWidth * (day % COLUMNS) + padLeftRight;
    int y1 = beginY + 3;

    // Setting text font
    display.setFont(&FreeSansBold18pt7b);

    //    // Draw background // lascio commentato, risulta troppo scuro
    //    display.fillRect(x1, y1, cellWidth - 2 * padLeftRight, 110, 6);

        // Some temporary variables
    int n = 0;
    char line[128];

    // Insert line brakes into setTextColor
    int lastSpace = -100;
    display.setCursor(x1 + 5, beginY + 45);
    for (int i = 0; i < min((size_t)64, strlen(event->name)); ++i)
    {
        // Copy name letter by letter and check if it overflows space given
        line[n] = event->name[i];
        if (line[n] == ' ')
            lastSpace = n;
        line[++n] = 0;

        int16_t xt1, yt1;
        uint16_t w, h;

        // Gets text bounds
        display.getTextBounds(line, 0, 0, &xt1, &yt1, &w, &h);

        // Char out of bounds, put in next line
        if (w > cellWidth - 2 * padLeftRight - 42) // cambiare l'ultimo numero che cambiare quando andare a capo
        {
            // if there was a space 5 chars before, break line there
            if (n - lastSpace < 5)
            {
                i -= n - lastSpace - 1;
                line[lastSpace] = 0;
            }

            // Print text line
            display.setCursor(x1 + 5, display.getCursorY());
            display.println(line);

            // Clears line (null termination on first charachter)
            line[0] = 0;
            n = 0;
        }
    }

    // display last line of text
    display.setCursor(x1 + 5, display.getCursorY());
    display.println(line);

    // Set cursor on same y but change x
    display.setCursor(x1 + 5, display.getCursorY() - 10);
    display.setFont(&FreeSans12pt7b);

    // Print time
    // also, if theres a location print it
    if (strlen(event->location) != 1)
    {
        display.println(event->time);

        display.setCursor(x1 + 5, display.getCursorY());

        char line[128] = { 0 };

        for (int i = 0; i < strlen(event->location); ++i)
        {
            line[i] = event->location[i];
            line[i + 1] = 0;

            int16_t xt1, yt1;
            uint16_t w, h;

            // Gets text bounds
            display.getTextBounds(line, 0, 0, &xt1, &yt1, &w, &h);

            if (w > (WIDTH / COLUMNS))
            {
                for (int j = i - 1; j > max(-1, i - 4); --j)
                    line[j] = '.';
                line[i] = 0;
            }
        }

        display.print(line);
    }
    else
    {
        display.print(event->time);
    }

    int bx1 = x1;
    int by1 = y1;
    int bx2 = x1 + cellWidth - 2 * padLeftRight;
    int by2 = display.getCursorY() + 7;

    // Draw event rect bounds
    display.drawThickLine(bx1, by1, bx1, by2, 3, thickLineGrid);
    display.drawThickLine(bx1, by2, bx2, by2, 3, thickLineGrid);
    display.drawThickLine(bx2, by2, bx2, by1, 3, thickLineGrid);
    display.drawThickLine(bx2, by1, bx1, by1, 3, thickLineGrid);

    // Set how high is the event
    *heigthNeeded = display.getCursorY() + 12 - y1;

    // Return is it overflowing
    return display.getCursorY() < maxHeigth - 100; // ipotizzo che il prossimo evento sia alto 100 pixel
}

// Struct event comparison function, by timestamp, used for qsort later on
int cmp(const void* a, const void* b)
{
    entry* entryA = (entry*)a;
    entry* entryB = (entry*)b;

    return (entryA->timeStamp - entryB->timeStamp);
}

// Main data drawing data
void drawCalendarData()
{
    long i = 0;
    long n = strlen(data);

    // Parso gli ultimi 70k caratteri. Oltre sono troppo vecchi.
    /*if (n > 70000)
        n = 70000;*/

        // reset count
    entriesNum = 0;

    // Search raw data for events
    while (entriesNum < MAX_CALENDAR_EVENTS && i < n && strstr(data + i, "BEGIN:VEVENT"))
    {
        // Find next event start and end
        i = strstr(data + i, "BEGIN:VEVENT") - data + 12;
        char* end = strstr(data + i, "END:VEVENT");

        if (end == NULL)
            continue;

        bool correggiTimeZone = true;
        // Find all relevant event data
        char* summary = strstr(data + i, "SUMMARY:") + 8;
        char* location = strstr(data + i, "LOCATION:") + 9;

        // Dopo il DTSTART potrebbero esserci dei parametri, quindi li cerco.
        char* timeStart = strstr(data + i, "DTSTART") + 7;

        // Se esiste il campo TZID devo riportare l'orario senza correggerlo tramite TimeZone.
        // Il parametro ;VALUE=DATE indica che non è presente l'orario perché l'evento occupa tutto il giorno.
        if (stringContain(timeStart, ";TZID") || stringContain(timeStart, ";VALUE=DATE"))
        {
            correggiTimeZone = false;
        }
        timeStart = strstr(timeStart, ":") + 1;


        char* timeEnd = strstr(data + i, "DTEND") + 5;
        timeEnd = strstr(timeEnd, ":") + 1;

        // Gestisco gli eventi ripetuti nel tempo
//        char *rRule = strstr(data + i, "RRULE:") + 6;
//        byte giorniFrequenzaRipetizione = 0;
//        if (rRule && rRule < end)
//        {
//          if (stringContain(rRule, "FREQ=WEEKLY"))
//          {
//            giorniFrequenzaRipetizione = 7;
//          } else if (stringContain(rRule, "FREQ=DAILY")) {
//            giorniFrequenzaRipetizione = 1;
//          }
//        }
        // Sequenza
//        char *sequence = strstr(data + i, "SEQUENCE:") + 9;
//        Serial.print("Sequence: ");
//        Serial.println(sequence);
//        Serial.print("Frequence: ");
//        Serial.println(giorniFrequenzaRipetizione);

//        for (int seq = 0; seq <= atoi(sequence)


        if (summary && summary < end)
        {
            strncpy(entries[entriesNum].name, summary, strchr(summary, '\n') - summary);
            entries[entriesNum].name[strchr(summary, '\n') - summary] = 0;
        }
        if (location && location < end)
        {
            strncpy(entries[entriesNum].location, location, strchr(location, '\n') - location);
            entries[entriesNum].location[strchr(location, '\n') - location] = 0;
        }

        //Serial.print("DEBUG DTSTART ");
        if (timeStart && timeStart < end && timeEnd < end)
        {
            //Serial.println(tempDebug);
            getToFrom(entries[entriesNum].time, timeStart, timeEnd, &entries[entriesNum].day,
                &entries[entriesNum].timeStamp, correggiTimeZone);
        }
        ++entriesNum;
    }

    // Sort entries by time
    qsort(entries, entriesNum, sizeof(entry), cmp);
    Serial.print("Eventi nel calendario: ");
    Serial.println(entriesNum);

    // Events displayed and overflown counters
    int columns[COLUMNS * ROWS] = { 0 };
    bool clogged[COLUMNS * ROWS] = { 0 };
    int cloggedCount[COLUMNS * ROWS] = { 0 };

    // Displaying events one by one
    for (int i = 0; i < entriesNum; ++i)
    {
        //Serial.println(entries[i].day);
        // If column overflowed just add event to not shown
        if (entries[i].day != -1 && clogged[entries[i].day])
            ++cloggedCount[entries[i].day];
        if (entries[i].day == -1 || clogged[entries[i].day])
            continue;

        // We store how much height did one event take up
        int shift = 0;
        int padDown = 5;
        int padUp = 8;
        bool s = drawEvent(&entries[i], entries[i].day, columns[entries[i].day] + (entries[i].day / COLUMNS) * cellHeight + marginUp + headerCalendarName + headerDay + headerWeather + padUp,
            (entries[i].day / COLUMNS) * cellHeight + marginUp + headerCalendarName + cellHeight, &shift);

        Serial.println(shift);
        columns[entries[i].day] += shift + padDown;

        // If it overflowed, set column to clogged and add one event as not shown
        if (!s)
        {
            Serial.println("Clogged event");
            //            ++cloggedCount[entries[i].day];
            clogged[entries[i].day] = 1;
        }
    }

    // Display not shown events info
    for (int i = 0; i < COLUMNS * ROWS; ++i)
    {
        if (clogged[i] && cloggedCount[i] > 0)
        {
            // Draw notification showing that there are more events than drawn ones
            int xBegin = marginLeft + cellWidth * (i % COLUMNS) + thickLineGrid;
            int yBegin = marginUp + headerCalendarName + (i / COLUMNS) * cellHeight + cellHeight - 23;
            display.fillRoundRect(5 + xBegin, yBegin, cellWidth - 10, 20, 10, 6);
            display.setCursor(15 + xBegin, yBegin + 15);
            //            display.setTextColor(7, 0);
            display.setTextColor(BLACK, WHITE);
            display.setFont(&FreeSans9pt7b);
            display.print(cloggedCount[i]);
            display.print(" more event");
            // Se c'è più di un evento, metto il plurale ad events
            if (cloggedCount[i] > 1)
            {
                display.print("s");
            }
        }
    }
}

// ====  WEATHER drawing  ====
// ICON
void drawWeatherIcon(int beginX, int beginY, int day)
{
    int color = 3;
    // Icon
    for (int i = 0; i < 11; ++i)
    {
        // If found draw specified icon
        if (strcmp(abbr_days[day], abbrs[i]) == 0)
            display.drawBitmap(beginX, beginY, color_icons[i], icon_height, icon_height, color);
    }
}
// weather info label
void drawWeatherLabel(int x, int y, int day)
{
    //    // Searching for weather state abbreviation
    //    for (int i = 0; i < 10; ++i)
    //    {
    //        // If found draw specified icon
    //        if (strcmp(abbrs[i], currentWeatherAbbr) == 0)
    //            display.drawBitmap(50, 50, logos[i], 152, 152, BLACK);
    //    }

        // Draw weather state
    display.setTextColor(BLACK, WHITE);
    display.setFont(&FreeSans18pt7b);
    display.setTextSize(1);
    display.setCursor(x, y);
    display.println(nameWeather[day]);

}
// TEMPERATURE
void drawWeatherTemp(int x, int y, int day)
{
    // Temp Max
    display.setFont(&FreeSans18pt7b);
    display.setCursor(x, y);
    display.print(temps_max[day]);
    display.setFont(&FreeSans12pt7b);
    display.println("° C");
    // Temp Min
    display.setFont(&FreeSans18pt7b);
    display.setCursor(x, y + 40);
    display.print(temps_min[day]);
    display.setFont(&FreeSans12pt7b);
    display.println(F("° C"));
}
// PREDICTABILITY
void drawWeatherPredictability(int x, int y, int day)
{
    // Predictability
    display.setFont(&FreeSans18pt7b);
    display.setCursor(x, y);
    display.print(predictability[day]);
    display.setFont(&FreeSans12pt7b);
    display.println("%");
}

void drawWeatherStrip()
{
    int padLeft = 15;
    int padUp = -2;
    int padDown = 5;
    for (int day = 0; day < COLUMNS * ROWS; day++)
    {
        int xBegin = marginLeft + cellWidth * (day % COLUMNS) + padLeft;
        int yBegin = marginUp + headerCalendarName + headerDay + (day / COLUMNS) * cellHeight + padUp;
        drawWeatherIcon(xBegin, yBegin, day);
        drawWeatherLabel(xBegin, yBegin + headerWeather - 10, day);
        drawWeatherTemp(xBegin + icon_height + 20, yBegin + 40, day);
        drawWeatherPredictability(xBegin + icon_height + 88, yBegin + 60, day);

        // Riga orizzontale in basso. Delimita tempo da eventi calendario
        display.drawThickLine(xBegin - padLeft + thickLineGrid, yBegin + headerWeather + padDown, xBegin - padLeft + cellWidth, yBegin + headerWeather + padDown, colorGrid + 3, thickLineGrid);
    }
}

