#ifndef ICONS_H
#define ICONS_H

#include "binary_Icons/icon_C.h"
#include "binary_Icons/icon_H.h"
#include "binary_Icons/icon_Hc.h"
#include "binary_Icons/icon_Hr.h"
#include "binary_Icons/icon_Lc.h"
#include "binary_Icons/icon_Lr.h"
#include "binary_Icons/icon_S.h"
#include "binary_Icons/icon_Sl.h"
#include "binary_Icons/icon_Sn.h"
#include "binary_Icons/icon_T.h"

#include "binary_Icons/icon_S_C.h"
#include "binary_Icons/icon_S_H.h"
#include "binary_Icons/icon_S_Hc.h"
#include "binary_Icons/icon_S_Hr.h"
#include "binary_Icons/icon_S_Lc.h"
#include "binary_Icons/icon_S_Lr.h"
#include "binary_Icons/icon_S_S.h"
#include "binary_Icons/icon_S_Sl.h"
#include "binary_Icons/icon_S_Sn.h"
#include "binary_Icons/icon_S_T.h"

// MOON PHASES
#include "binary_Icons/moon_phases/moon_phase_0.h"
#include "binary_Icons/moon_phases/moon_phase_0_04.h"
#include "binary_Icons/moon_phases/moon_phase_0_08.h"
#include "binary_Icons/moon_phases/moon_phase_0_11.h"
#include "binary_Icons/moon_phases/moon_phase_0_15.h"
#include "binary_Icons/moon_phases/moon_phase_0_18.h"
#include "binary_Icons/moon_phases/moon_phase_0_21.h"
#include "binary_Icons/moon_phases/moon_phase_0_25.h"
#include "binary_Icons/moon_phases/moon_phase_0_29.h"
#include "binary_Icons/moon_phases/moon_phase_0_33.h"
#include "binary_Icons/moon_phases/moon_phase_0_36.h"
#include "binary_Icons/moon_phases/moon_phase_0_40.h"
#include "binary_Icons/moon_phases/moon_phase_0_43.h"
#include "binary_Icons/moon_phases/moon_phase_0_47.h"
#include "binary_Icons/moon_phases/moon_phase_0_50.h"
#include "binary_Icons/moon_phases/moon_phase_0_54.h"
#include "binary_Icons/moon_phases/moon_phase_0_58.h"
#include "binary_Icons/moon_phases/moon_phase_0_61.h"
#include "binary_Icons/moon_phases/moon_phase_0_65.h"
#include "binary_Icons/moon_phases/moon_phase_0_69.h"
#include "binary_Icons/moon_phases/moon_phase_0_73.h"
#include "binary_Icons/moon_phases/moon_phase_0_77.h"
#include "binary_Icons/moon_phases/moon_phase_0_81.h"
#include "binary_Icons/moon_phases/moon_phase_0_85.h"
#include "binary_Icons/moon_phases/moon_phase_0_89.h"
#include "binary_Icons/moon_phases/moon_phase_0_93.h"
#include "binary_Icons/moon_phases/moon_phase_0_96.h"

#endif
